server:
  port: 8082

spring:
  application:
    name: account
  datasource-postgres:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/storage
    username: root
    password: root