server:
  port: 8080

spring:
  application:
    name: gateway
  datasource-postgres:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5434/storage
    username: root
    password: root

#Feign Account service
account:
  create: /account/{customerId}
  find:
    customer:
      by:
        id: /account/customer/{customerId}
  service:
    feign:
      client:
        name: Account-Service
    url: http://localhost:8082

#Feign Transaction service
transaction:
  create: /transaction/customer/{customerId}/account/{accountId}/{amount}
  find:
    account:
      balance: /transaction/account/{accountId}/balance
    customer:
      balance: /transaction/customer/{customerId}/
  service:
    feign:
      client:
        name: Transaction-Service
    url: http://localhost:8084