server:
  port: 8084

spring:
  application:
    name: transaction
  datasource-postgres:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/storage
    username: root
    password: root